name: CD Workflow

on:
  workflow_run:
    workflows:
      - CI Workflow
    types:
      - completed

jobs:
  cd-deploy-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    name: Deploy to PROD
    runs-on: ubuntu-latest
    environment: hastus_prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel

      - name: Validate required secrets exist
        run: |
          [ -n "${{ secrets.HASTUS_HOST }}" ] || (echo "Missing secret: HASTUS_HOST" && exit 1)
          [ -n "${{ secrets.HASTUS_CLIENT_ID }}" ] || (echo "Missing secret: HASTUS_CLIENT_ID" && exit 1)
          [ -n "${{ secrets.HASTUS_CLIENT_SECRET }}" ] || (echo "Missing secret: HASTUS_CLIENT_SECRET" && exit 1)

      - name: Configure Databricks
        run: |
          # write out the profile (here called "PROD")
          cat <<EOF > ~/.databrickscfg
          [PROD]
          host = ${{ secrets.HASTUS_HOST }}
          client_id = ${{ secrets.HASTUS_CLIENT_ID }}
          client_secret = ${{ secrets.HASTUS_CLIENT_SECRET }}
          EOF

      - name: Deploy to PROD
        run: |
          databricks bundle deploy \
            --target prod \
            --profile PROD
