name: CI Workflow

on:
  push:
    branches:
      - "feature/**"
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ci_job:
    name: CI Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Java 17 for PySpark
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install dependencies + pytest-html
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-venv-pyspark.txt
          pip install pytest-html

      - name: Run pytest & generate HTML report
        run: |
          pytest \
            --disable-warnings \
            --cov=./src \
            --cov-report=html

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
